### ISSUE TITLE
Docker build image tag is not get set correctly

### ISSUE THREAD

**Issue by ryan-talley** [F5Networks/marathon-bigip-ctlr#246]
#### Description
The docker image tag that is set in build-runtime-images.sh is not being set properly with `${VERSION_BUILD_ARGS}`. This is causing the docker tag to be set to `<no' 'value>'` which is then passed to the systest Makefile as `bigip_ctlr_tag=<no' 'value>'` which is then used as an argument to run_systests.sh as an argument to what directory the tests to be run are in. This results in the invalid directory of `marathon_bigip_ctlr_master_marathon_functest_v12_1_0_<no` and none of the marathon systests are run.

**Comment by ryan-talley** [comment]
Adding @amudukutore

**Comment by edarzins** [comment]
The BUILD_STAMP was removed in commit eeae167, added it back. PR submitted.

**Comment by ryan-talley** [comment]
Fixed by https://github.com/F5Networks/marathon-bigip-ctlr/pull/247#event-1378155325
