### ISSUE TITLE
Documentation request on scalability

### ISSUE THREAD

**Issue by mrajagopal** [F5Networks/marathon-bigip-ctlr#276]
#### Description
F5 BIG-IP Controller for Marathon
http://clouddocs.f5.com/products/connectors/marathon-bigip-ctlr/v1.2/

Please clarify the following items and update the documentation:
1. Could single CC be able to manage several BIGIPs?
   Reading the docs suggests that (implicitly) its a 1-1 mapping i.e. one bigip-controller to one BIG-IP.
   It is possible to use multiple BIG-IP Controller instances to manage separate BIG-IP partitions.
   Unclear if this implies a separate BIG-IP itself.

2. Is there any sizing guide about the CC performance?
   I have not found a suitable sizing guide for this. Please advise.

3. Is there any high availability solution for CC?
   Please confirm that there is NO high availability feature for the marathon CC.

#### Mesos Version
1.0.1 

#### Marathon Version
1.2.1

#### Controller Version
1.1.0

#### BIG-IP Version
v12.1.2

#### Diagnostic Information
Nt applicable

**Comment by sjsharma2001** [comment]
Managing multiple BIG-IPs: (from @edarzins) A single CC can manage no more than one BIG-IP. However, a single CC can manage multiple partitions on one BIG-IP. You can also use several CC's to manage one BIG-IP (for example, one CC per partition).

High availability: tracked via https://github.com/F5Networks/f5-ci-docs/issues/350

**Comment by sjsharma2001** [comment]
Responded to Madhu about sizing guide information. Given everything is either addressed or tracked elsewhere, I am closing this.
