### ISSUE TITLE
Clouddocs showing incorrect version of Marathon controller

### ISSUE THREAD

**Issue by sjsharma2001** [F5Networks/marathon-bigip-ctlr#281]
#### Description
Clouddocs is showing incorrect version of Marathon controller (v1.2.1)

#### Mesos Version
Any

#### Marathon Version
Any

#### Controller Version
v.1.2.0

#### BIG-IP Version
Any

#### Diagnostic Information
Visit http://clouddocs.f5.com/products/connectors/marathon-bigip-ctlr/v1.2/
It shows "F5 BIG-IP Controller for Marathon v1.2.1" in the left frame.
It should show the correct version (v1.2.0)

**Comment by amudukutore** [comment]
Fixed as part of https://github.com/F5Networks/marathon-bigip-ctlr/pull/280.
