### ISSUE TITLE
Marathon BigIP Controller 1.1.1 breaks if health check has 'MESOS_HTTP' as protocol

### ISSUE THREAD

**Issue by frankmesen** [F5Networks/marathon-bigip-ctlr#314]
#### Description
Marathon BigIP Controller version 1.1.1 throws an error and doesn't configure an app if its health check is using protocol 'MESOS_HTTP'

Additional information:
DC/OS supports the following protocols for health checks:
MESOS_HTTP
MESOS_HTTPS
MESOS_TCP

Source: https://docs.mesosphere.com/1.10/deploying-services/creating-services/health-checks/)

The protocols 'http', https' and 'tcp' are deprecated for health checks on DC/OS version 1.10 and up.

#### Mesos Version
1.4.0

#### Marathon Version
1.5.2

#### Controller Version
1.1.1

#### BIG-IP Version
BIG-IP 12.1.1 Build 1.0.196 Hotfix HF1

#### Diagnostic Information
Error:
```
2018-03-15 01:40:36,860 controller: ERROR   : CCCL Error: Service congifuration provided does not match schema: u'mesos_http' is not one of ['http', 'tcp', 'https', 'icmp', 'udp']

Failed validating 'enum' in schema['properties']['monitors']['items']['properties']['type']:
    {'description': 'Specifies the type of the monitor.',
     'enum': ['http', 'tcp', 'https', 'icmp', 'udp'],
     'type': 'string'}

```

How to reproduce the error:
Change a health check to use protocol 'MESOS_HTTP' and check the Marathon BigIP Controller
Snippet:
```
 "healthChecks": [
    {
      "gracePeriodSeconds": 300,
      "intervalSeconds": 20,
      "maxConsecutiveFailures": 10,
      "portIndex": 0,
      "timeoutSeconds": 10,
      "delaySeconds": 15,
      "protocol": "MESOS_HTTP",
      "path": "/"
    }
  ]
```

**Comment by edarzins** [comment]
@frankmesen HTTP, HTTPS, and TCP are not deprecated. Those protocols define "Marathon-level" health checks. MESOS_HTTP, MESOS_HTTPS, and MESOS_TCP are different in that they define "Mesos level" health checks.
